<h1>Security settings</h1>
<p>
To prevent access by unauthorized entities, please enter a username and password. Remember this password well, you will need it in the future if you are to change any important setting.
</p>
<form method='POST'>
   <input type='hidden' name='step' value='4' />
   <label for='username'>Username</label><input name='username' />
   <label for='password'>Password</label><input name='password' />
   <input type='submit' value='Save and continue' />
</form>
