<h1>Beveiligings-instellingen</h1>
<p>
    Om de toegang voor onbevoegden af te schermen, dient u een zelf te kiezen gebruikersnaam en wachtwoord op te geven. Onthoud dit wachtwoord goed, u hebt het in het vervolg altijd nodig als u belangrijke instellingen aan wilt passen.
</p>
<form method='POST'>
   <input type='hidden' name='step' value='4' />
   <label for='username'>Gebruikersnaam</label><input name='username' />
   <label for='password'>Wachtwoord</label><input name='password' />
   <input type='submit' value='Opslaan en verder' />
</form>
