<h1>Installatie voltooid!</h1>
<p>
Gefeliciteerd, de installatie is voltooid! De URL naar het superbeheer is
</p>
<p>
<a href='<?php echo $url."superadminarea/"; ?>'><?php echo $url."superadminarea/"; ?></a>
</p>
<p>
U dient hier in te loggen met de eerder ingevoerde combinatie van gebruikersnaam en wachtwoord.
</p>
<?php

    /*
        <p>
        Als u een andere map wilt gebruiken, kunt u onderstaand de gewenste URL ingeven.
        </p>
        <form method='POST'>
           <input type='hidden' name='step' value='6' />
          http://localhost<input name='url' value='<?php echo truepath($_SERVER["REQUEST_URI"] . "/../"); ?>'></input>/superadminarea
           <p> </p>
           <input type='submit' value='Opslaan en klaar' />
        </form>
    */

?>
