<h1>Installation completed!</h1>
<p>
Congratulations, the installation is complete! The URL to the superadminarea is
</p>
<p>
<a href='<?php echo $url."/superadminarea/"; ?>'><?php echo $url."/superadminarea/"; ?></a>
</p>
<p>
You should login with the username and password combination as entered in an earlier step.
</p>
<?php

    /*
        <p>
        if you wish to use another folder, please enter the preferred URL below.
        </p>
        <form method='POST'>
           <input type='hidden' name='step' value='6' />
          http://localhost<input name='url' value='<?php echo truepath($_SERVER["REQUEST_URI"] . "/../"); ?>'></input>/superadminarea
           <p> </p>
           <input type='submit' value='Opslaan en klaar' />
        </form>
    */

?>
